"""
ExtractorAgent module.

This agent is built on RAG for knowledge retrieval.
It retrieves similar examples from the knowledge base to guide extraction.
"""

import json
import re
from typing import Any, Optional, List
from agentscope.agents import AgentBase
from agentscope.message import Msg
from agentscope.models import ModelResponse
from agentscope.prompt import PromptEngine
from agentscope.rag import KnowledgeBank
from agentscope.rag import Knowledge
from knowledge.knowledge_base import KnowledgeBase
from loguru import logger

# Prompt for checking if the content is retrieved from the input text
CHECKING_PROMPT = (
    "Is the content retrieved from the input text?\n"
    "Retrieved content: {retrieved}\n"
    "Input text: {query}\n"
    "Please answer YES or NO."
)

class ExtractorAgent(AgentBase):

    def __init__(
        self,
        name: str,
        sys_prompt: str,
        model_config_name: str,
        knowledge_list: list[Knowledge] = None,
        knowledge_id_list: list[str] = None,
        similarity_top_k: int = None,
        log_retrieval: bool = True,
        recent_n_mem_for_retrieve: int = 1,
        **kwargs: Any,
    ) -> None:
        """
        Initializes the extractorAgent with the given parameters.

        Args:
            name (str): Name of the agent.
            sys_prompt (str): System prompt for the agent.
            model_config_name (str): Model configuration name.
            knowledge_list (list[Knowledge], optional): List of knowledge examples.
            knowledge_id_list (list[str], optional): List of knowledge IDs.
            similarity_top_k (int, optional): Number of top similar examples to retrieve.
            log_retrieval (bool, optional): Whether to log retrieval details.
            recent_n_mem_for_retrieve (int, optional): Number of recent memories for retrieval.
        """
        super().__init__(
            name=name,
            sys_prompt=sys_prompt,
            model_config_name=model_config_name,
        )
        self.knowledge_list = knowledge_list or []
        self.knowledge_id_list = knowledge_id_list or []
        self.similarity_top_k = similarity_top_k
        self.log_retrieval = log_retrieval
        self.recent_n_mem_for_retrieve = recent_n_mem_for_retrieve
        self.description = kwargs.get("description", "")

    def parse_json(self, response: ModelResponse) -> ModelResponse:
        """
        Parse the JSON data from the model response.

        Args:
            response (ModelResponse): The model's response containing the text.

        Returns:
            ModelResponse: The parsed response in JSON format.
        """
        # Regular expression to extract JSON data from the response
        pattern = r"```json(.*)```"
        match = re.search(pattern, response.text, re.DOTALL)
        json_text = match.group(1) if match else response.text
        resu=ModelResponse(text=json_text)
        return resu

    def generate_prompt(self, text):
        """
        Generate a prompt for knowledge retrieval from the knowledge base.

        Args:
            text (str): The input text for which similar examples are to be retrieved.

        Returns:
            str: The generated prompt.
        """
        kb = KnowledgeBase('./knowledge/knowledge_base.json')
        similar_example = kb.search_similar(text)
        if similar_example:
            prompt = json.dumps(similar_example, ensure_ascii=False)
        else:
            prompt = """ """
        return prompt

    def reply(self, x: dict = None) -> dict:
        """
        Process the input data, retrieve relevant knowledge examples, and generate a response.

        Args:
            x (dict, optional): The input data containing the text to be processed.

        Returns:
            dict: The response generated by the agent.
        """
        retrieved_docs_to_string = ""

        # If memory is enabled, retrieve the most recent memory or use the input as query
        if self.memory:
            self.memory.add(x)
            history = self.memory.get_memory(
                recent_n=self.recent_n_mem_for_retrieve,
            )
            query = (
                "/n".join(
                    [msg["content"] for msg in history],
                )
                if isinstance(history, list)
                else str(history)
            )
        elif x is not None:
            query = x["content"]
        else:
            query = ""

        if len(query) > 0:
            # If content has information, perform knowledge retrieval
            scores = []
            for knowledge in self.knowledge_list:
                retrieved_nodes = knowledge.retrieve(
                    str(query),
                    self.similarity_top_k,
                )
                for node in retrieved_nodes:
                    scores.append(node.score)
                    retrieved_docs_to_string += (
                        "\n>>>> score:"
                        + str(node.score)
                        + "\n>>>> source:"
                        + str(node.node.get_metadata_str())
                        + "\n>>>> content:"
                        + node.get_content()
                    )

            # Log the retrieval details if logging is enabled
            if self.log_retrieval:
                self.speak("[retrieved]:" + retrieved_docs_to_string)

            # If the max similarity score is low, ask LLM to confirm relevance
            if max(scores) < 0.4:
                msg = Msg(
                    name="user",
                    role="user",
                    content=CHECKING_PROMPT.format(
                        retrieved_docs_to_string,
                        query,
                    ),
                )
                msg = self.model.format(msg)
                checking = self.model(msg)
                logger.info(checking)
                checking = checking.text.lower()
                if "no" in checking:
                    retrieved_docs_to_string = "EMPTY"

        # Prepare the prompt for extraction based on the input text
        self.engine = PromptEngine(self.model)

        sample_prompt = self.generate_prompt(x["content"])

        # Define the base prompt for the extraction task, recommending using Chinese prompt for coding test.
        baseprompt = """
        请按照下面的步骤进行，完成对{context}内的每一行的桥梁检测文本的实体、关系、属性提取任务：
        1- 根据给出的8个实体//构件编号（例如：1#、13-2#、第一跨）、构件（湿接缝）、构件部位（模板、底板、腹板、翼缘板、台顶、台帽、横梁）、病害位置（例如：距0#台处1.5m，距左侧人行道4m处、锚固区等）、病害、病害数量（例如：3条等）、病害性状描述类别（例如：宽度、长度、面积等）、病害性状数值（例如：3厘米、3.45平方米等）//进行实体识别；
        2- 根据给出的4个关系//构件位置是（构件到构件编号的关系)、具体部位是（构件编号到构件部位的关系）、病害具体位置是（构件部位到病害位置的关系）、存在病害是（病害位置到病害的关系）//进行关系识别
        3- //病害数量、病害性状描述类别、病害性状数值//3个实体为//病害//实体的属性，例如：（病害：数量：病害数量，病害性状描述类别：病害性状数值）
        4- 请按照给定输出样式，输出实体关系提取格式：```json 
        [{{
        "文本": "3#台处伸缩缝锚固区混凝土纵向裂缝，l=0.3m，W=0.15mm",
        "三元组": ["构件:伸缩缝>构件位置是>构件编号:3#台",
                  "构件编号:3#台>病害具体位置是>病害位置:锚固区混凝土",
                  "病害位置:锚固区混凝土>存在病害是>病害:纵向裂缝"],
        "属性": ["纵向裂缝>长度>0.3m",
                "纵向裂缝>宽度>0.15mm"]
        }},
        {{
        "文本": "3#支座脱空15%",
        "三元组": ["构件:支座>构件位置是>构件编号:3#", 
                  "构件编号:3#>存在病害是>病害:脱空"],
        "属性": ["脱空>脱空率>15%"]
        }}，
        {{
        "文本": "右侧人行道0#台处1处沉陷，H=3cm",
        "三元组": ["构件:人行道>构件位置是>构件编号:0#台", 
                  "构件编号:0#台>具体部位是>构件部位:右侧",
                  "构件部位:右侧>存在病害是>病害:脱空"],
        "属性": ["沉陷>数量>1处", "沉陷>高度>3cm"]   
        }}
        ] 
        ```
        5- 提取示例：可以对比是否和下述例子类似，如果类似则参考下述例子的提取规则。例子：{sample}
        5- 属性检查：对于//最大长度、最大宽度、总长度、总宽度，总面积//全部修改为//长度、宽度、面积//，删除修饰词
        6- 完成句子提取,请注意json格式的正确性，多条数据时最外层应该包含中括号
        只需要最终返回```json your_extraction_here ``` ,不需要给我其他任何内容。
        """

        # For english report. Recommending using Chinese prompt for coding test.
        baseprompt_en = """
        Please follow the steps below to complete the entity, relationship, and attribute extraction task for each line in the bridge inspection text within {context}:
        1- Perform entity recognition based on the 8 entities //element_number (such as: 1#, 13-2#, First Span), element (expansion joint), element_location (formwork, bottom plate, web, flange, top of the pier, cap of the pier, cross beam), defect_location (such as: 1.5m from 0# pier, 4m from the left sidewalk, anchorage zone, etc.), defect, defect_quantity (such as: 3 cracks, etc.), disease category (such as: width, length, area, etc.), disease value (such as: 3 cm, 3.45 m², etc.)//;
        2- Perform relationship recognition based on the 4 relations //element_location_is (relation between element and element number), specific_part_is (relation between element number and element part), defect_location_is (relation between element part and defect location), exists_defect_is (relation between defect location and defect)//;
        3- For //defect quantity, disease category, disease value//, these are attributes of the //defect// entity, such as: (defect: quantity: defect quantity, disease category: defect value);
        4- Please output the entity and relationship extraction format according to the given style: ```json 
        [{
            "texts": "At 3# pier, expansion joint anchorage zone, concrete longitudinal crack, l=0.3m, W=0.15mm",
            "triples": ["element: expansion_joint > element_location_is > element_number: 3#台",
                        "element_number: 3#台 > defect_location_is > defect_location: anchorage_zone_concrete",
                        "defect_location: anchorage_zone_concrete > exists_defect_is > defect: longitudinal_crack"],
            "properties": ["longitudinal_crack > length > 0.3m",
                           "longitudinal_crack > width > 0.15mm"]
        }, {
            "texts": "At 3# pier, bearing void 15%",
            "triples": ["element: bearing > element_location_is > element_number: 3#",
                        "element_number: 3# > exists_defect_is > defect: void"],
            "properties": ["void > void_ratio > 15%"]
        }, {
            "texts": "At 0# pier, right sidewalk, 1 subsidence, H=3cm",
            "triples": ["element: sidewalk > element_location_is > element_number: 0#台",
                        "element_number: 0#台 > specific_part_is > element_part: right_side",
                        "element_part: right_side > exists_defect_is > defect: subsidence"],
            "properties": ["subsidence > quantity > 1", "subsidence > height > 3cm"]
        }]
        """

        self.engine = PromptEngine(self.model)
        variables = {"context": x.content, "sample": sample_prompt}

        finalprompt = self.engine.join(
            baseprompt, format_map=variables
        )

        # prepare prompt
        prompt = self.model.format(
            Msg(
                name="system",
                role="system",
                content=self.sys_prompt,
            ),
            self.memory.get_memory(
                recent_n=self.recent_n_mem_for_retrieve,
            ),
            Msg(
                name="user",
                role="user",
                content="Context: " + retrieved_docs_to_string,
            ),
            Msg("system", finalprompt, role="system"),
        )

        response = self.model(prompt,parse_func=self.parse_json,).text

        msg = Msg(self.name, response, role="extractor")

        self.speak(msg)

        if self.memory:
            self.memory.add(msg)

        return msg
